In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
data = pd.read_csv("dirty_cafe_sales.csv")
print(data.isnull().sum())

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [58]:
data = data.drop('Transaction ID', axis=1, errors='ignore')
data_clone = data.copy()
data2 = ['Item', 'Payment Method', 'Location']
data3 = ['Quantity', 'Price Per Unit', 'Total Spent']
print(data['Quantity'].dtype)

str

In [59]:
for col in data.columns:
    data[col] = data[col].replace(['ERROR', 'UNKNOWN'], np.nan)
    data_clone[col] = data_clone[col].replace(['ERROR', 'UNKNOWN'], np.nan)


for col in data2:
    data[col] = data[col].fillna(data[col].mode()[0])

for col in data3:
    data[col] = pd.to_numeric(data[col]) 
    data[col] = data[col].fillna(data[col].median())

data = data.dropna(subset=['Transaction Date'])

In [60]:
# item = {'Coffee':1,'Cake':2,'Cookie':3,'Salad':4,'Smoothie':5,'Sandwich':6,'Juice':7}
# data['Item'] = data['Item'].map(item)

# payment = {'Credit Card':1,'Cash':2,'Digital Wallet':3}
# data['Payment Method'] = data['Payment Method'].map(payment)

# location = {'Takeaway':1,'In-store':2}
# data['Location'] = data['Location'].map(location)
data.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19
3,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [61]:
data.drop_duplicates(inplace=True)

In [62]:
data['Item'].unique()
type=['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Juice', 'Sandwich', 'Tea']
dict={val:i for i,val in enumerate(type)}
data['Item']=data['Item'].map(dict)

In [63]:
data['Payment Method'].unique()
type=['Credit Card', 'Cash', 'Digital Wallet']
dict={val:i for i,val in enumerate(type)}
data['Payment Method']=data['Payment Method'].map(dict)

In [64]:
data['Location'].unique()
type=['Takeaway', 'In-store']
dict={val:i for i,val in enumerate(type)}
data['Location']=data['Location'].map(dict)

In [65]:
print(data.isnull().sum())

Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [66]:
data.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,0,2.0,2.0,4.0,0,0,2023-09-08
1,1,4.0,3.0,12.0,1,1,2023-05-16
2,2,4.0,1.0,8.0,0,1,2023-07-19
3,3,2.0,5.0,10.0,2,0,2023-04-27
4,0,2.0,2.0,4.0,2,1,2023-06-11